// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: human_agnostic.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HumanAgnostic_Generate_FullMethodName = "/HumanAgnostic/Generate"
)

// HumanAgnosticClient is the client API for HumanAgnostic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HumanAgnosticClient interface {
	Generate(ctx context.Context, in *HumanAgnosticRequest, opts ...grpc.CallOption) (*HumanAgnosticReply, error)
}

type humanAgnosticClient struct {
	cc grpc.ClientConnInterface
}

func NewHumanAgnosticClient(cc grpc.ClientConnInterface) HumanAgnosticClient {
	return &humanAgnosticClient{cc}
}

func (c *humanAgnosticClient) Generate(ctx context.Context, in *HumanAgnosticRequest, opts ...grpc.CallOption) (*HumanAgnosticReply, error) {
	out := new(HumanAgnosticReply)
	err := c.cc.Invoke(ctx, HumanAgnostic_Generate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HumanAgnosticServer is the server API for HumanAgnostic service.
// All implementations must embed UnimplementedHumanAgnosticServer
// for forward compatibility
type HumanAgnosticServer interface {
	Generate(context.Context, *HumanAgnosticRequest) (*HumanAgnosticReply, error)
	mustEmbedUnimplementedHumanAgnosticServer()
}

// UnimplementedHumanAgnosticServer must be embedded to have forward compatible implementations.
type UnimplementedHumanAgnosticServer struct {
}

func (UnimplementedHumanAgnosticServer) Generate(context.Context, *HumanAgnosticRequest) (*HumanAgnosticReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedHumanAgnosticServer) mustEmbedUnimplementedHumanAgnosticServer() {}

// UnsafeHumanAgnosticServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HumanAgnosticServer will
// result in compilation errors.
type UnsafeHumanAgnosticServer interface {
	mustEmbedUnimplementedHumanAgnosticServer()
}

func RegisterHumanAgnosticServer(s grpc.ServiceRegistrar, srv HumanAgnosticServer) {
	s.RegisterService(&HumanAgnostic_ServiceDesc, srv)
}

func _HumanAgnostic_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HumanAgnosticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanAgnosticServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HumanAgnostic_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanAgnosticServer).Generate(ctx, req.(*HumanAgnosticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HumanAgnostic_ServiceDesc is the grpc.ServiceDesc for HumanAgnostic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HumanAgnostic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HumanAgnostic",
	HandlerType: (*HumanAgnosticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _HumanAgnostic_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "human_agnostic.proto",
}
