// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: human_agnostic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HumanAgnosticRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cloth          []byte `protobuf:"bytes,1,opt,name=cloth,proto3" json:"cloth,omitempty"`
	Mask           []byte `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	Image          []byte `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	ImageParse     []byte `protobuf:"bytes,4,opt,name=image_parse,json=imageParse,proto3" json:"image_parse,omitempty"`
	ImagePose      []byte `protobuf:"bytes,5,opt,name=image_pose,json=imagePose,proto3" json:"image_pose,omitempty"`
	PoseJson       string `protobuf:"bytes,6,opt,name=pose_json,json=poseJson,proto3" json:"pose_json,omitempty"`
	ParseAgnostic  []byte `protobuf:"bytes,7,opt,name=parse_agnostic,json=parseAgnostic,proto3" json:"parse_agnostic,omitempty"`
	ImageDensepose []byte `protobuf:"bytes,8,opt,name=image_densepose,json=imageDensepose,proto3" json:"image_densepose,omitempty"`
}

func (x *HumanAgnosticRequest) Reset() {
	*x = HumanAgnosticRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_human_agnostic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanAgnosticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanAgnosticRequest) ProtoMessage() {}

func (x *HumanAgnosticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_human_agnostic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanAgnosticRequest.ProtoReflect.Descriptor instead.
func (*HumanAgnosticRequest) Descriptor() ([]byte, []int) {
	return file_human_agnostic_proto_rawDescGZIP(), []int{0}
}

func (x *HumanAgnosticRequest) GetCloth() []byte {
	if x != nil {
		return x.Cloth
	}
	return nil
}

func (x *HumanAgnosticRequest) GetMask() []byte {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *HumanAgnosticRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *HumanAgnosticRequest) GetImageParse() []byte {
	if x != nil {
		return x.ImageParse
	}
	return nil
}

func (x *HumanAgnosticRequest) GetImagePose() []byte {
	if x != nil {
		return x.ImagePose
	}
	return nil
}

func (x *HumanAgnosticRequest) GetPoseJson() string {
	if x != nil {
		return x.PoseJson
	}
	return ""
}

func (x *HumanAgnosticRequest) GetParseAgnostic() []byte {
	if x != nil {
		return x.ParseAgnostic
	}
	return nil
}

func (x *HumanAgnosticRequest) GetImageDensepose() []byte {
	if x != nil {
		return x.ImageDensepose
	}
	return nil
}

type HumanAgnosticReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HumanAgnosticReply) Reset() {
	*x = HumanAgnosticReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_human_agnostic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanAgnosticReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanAgnosticReply) ProtoMessage() {}

func (x *HumanAgnosticReply) ProtoReflect() protoreflect.Message {
	mi := &file_human_agnostic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanAgnosticReply.ProtoReflect.Descriptor instead.
func (*HumanAgnosticReply) Descriptor() ([]byte, []int) {
	return file_human_agnostic_proto_rawDescGZIP(), []int{1}
}

func (x *HumanAgnosticReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_human_agnostic_proto protoreflect.FileDescriptor

var file_human_agnostic_proto_rawDesc = []byte{
	0x0a, 0x14, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x5f, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x02, 0x0a, 0x14, 0x48, 0x75, 0x6d, 0x61, 0x6e,
	0x41, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x63, 0x6c, 0x6f, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x65, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e,
	0x70, 0x61, 0x72, 0x73, 0x65, 0x5f, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x73, 0x65, 0x41, 0x67, 0x6e, 0x6f, 0x73,
	0x74, 0x69, 0x63, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x65, 0x6e,
	0x73, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x44, 0x65, 0x6e, 0x73, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x22, 0x2e, 0x0a, 0x12,
	0x48, 0x75, 0x6d, 0x61, 0x6e, 0x41, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x49, 0x0a, 0x0d,
	0x48, 0x75, 0x6d, 0x61, 0x6e, 0x41, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x12, 0x38, 0x0a,
	0x08, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x48, 0x75, 0x6d, 0x61,
	0x6e, 0x41, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x41, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_human_agnostic_proto_rawDescOnce sync.Once
	file_human_agnostic_proto_rawDescData = file_human_agnostic_proto_rawDesc
)

func file_human_agnostic_proto_rawDescGZIP() []byte {
	file_human_agnostic_proto_rawDescOnce.Do(func() {
		file_human_agnostic_proto_rawDescData = protoimpl.X.CompressGZIP(file_human_agnostic_proto_rawDescData)
	})
	return file_human_agnostic_proto_rawDescData
}

var file_human_agnostic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_human_agnostic_proto_goTypes = []interface{}{
	(*HumanAgnosticRequest)(nil), // 0: HumanAgnosticRequest
	(*HumanAgnosticReply)(nil),   // 1: HumanAgnosticReply
}
var file_human_agnostic_proto_depIdxs = []int32{
	0, // 0: HumanAgnostic.Generate:input_type -> HumanAgnosticRequest
	1, // 1: HumanAgnostic.Generate:output_type -> HumanAgnosticReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_human_agnostic_proto_init() }
func file_human_agnostic_proto_init() {
	if File_human_agnostic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_human_agnostic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanAgnosticRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_human_agnostic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanAgnosticReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_human_agnostic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_human_agnostic_proto_goTypes,
		DependencyIndexes: file_human_agnostic_proto_depIdxs,
		MessageInfos:      file_human_agnostic_proto_msgTypes,
	}.Build()
	File_human_agnostic_proto = out.File
	file_human_agnostic_proto_rawDesc = nil
	file_human_agnostic_proto_goTypes = nil
	file_human_agnostic_proto_depIdxs = nil
}
