// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: mask.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ClothSegmentation_Generate_FullMethodName = "/ClothSegmentation/Generate"
)

// ClothSegmentationClient is the client API for ClothSegmentation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClothSegmentationClient interface {
	Generate(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageReply, error)
}

type clothSegmentationClient struct {
	cc grpc.ClientConnInterface
}

func NewClothSegmentationClient(cc grpc.ClientConnInterface) ClothSegmentationClient {
	return &clothSegmentationClient{cc}
}

func (c *clothSegmentationClient) Generate(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageReply, error) {
	out := new(ImageReply)
	err := c.cc.Invoke(ctx, ClothSegmentation_Generate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClothSegmentationServer is the server API for ClothSegmentation service.
// All implementations must embed UnimplementedClothSegmentationServer
// for forward compatibility
type ClothSegmentationServer interface {
	Generate(context.Context, *ImageRequest) (*ImageReply, error)
	mustEmbedUnimplementedClothSegmentationServer()
}

// UnimplementedClothSegmentationServer must be embedded to have forward compatible implementations.
type UnimplementedClothSegmentationServer struct {
}

func (UnimplementedClothSegmentationServer) Generate(context.Context, *ImageRequest) (*ImageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedClothSegmentationServer) mustEmbedUnimplementedClothSegmentationServer() {}

// UnsafeClothSegmentationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClothSegmentationServer will
// result in compilation errors.
type UnsafeClothSegmentationServer interface {
	mustEmbedUnimplementedClothSegmentationServer()
}

func RegisterClothSegmentationServer(s grpc.ServiceRegistrar, srv ClothSegmentationServer) {
	s.RegisterService(&ClothSegmentation_ServiceDesc, srv)
}

func _ClothSegmentation_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClothSegmentationServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClothSegmentation_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClothSegmentationServer).Generate(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClothSegmentation_ServiceDesc is the grpc.ServiceDesc for ClothSegmentation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClothSegmentation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClothSegmentation",
	HandlerType: (*ClothSegmentationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _ClothSegmentation_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mask.proto",
}
