// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: parse.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HumanParse_Generate_FullMethodName = "/HumanParse/Generate"
)

// HumanParseClient is the client API for HumanParse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HumanParseClient interface {
	Generate(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseReply, error)
}

type humanParseClient struct {
	cc grpc.ClientConnInterface
}

func NewHumanParseClient(cc grpc.ClientConnInterface) HumanParseClient {
	return &humanParseClient{cc}
}

func (c *humanParseClient) Generate(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseReply, error) {
	out := new(ParseReply)
	err := c.cc.Invoke(ctx, HumanParse_Generate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HumanParseServer is the server API for HumanParse service.
// All implementations must embed UnimplementedHumanParseServer
// for forward compatibility
type HumanParseServer interface {
	Generate(context.Context, *ParseRequest) (*ParseReply, error)
	mustEmbedUnimplementedHumanParseServer()
}

// UnimplementedHumanParseServer must be embedded to have forward compatible implementations.
type UnimplementedHumanParseServer struct {
}

func (UnimplementedHumanParseServer) Generate(context.Context, *ParseRequest) (*ParseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedHumanParseServer) mustEmbedUnimplementedHumanParseServer() {}

// UnsafeHumanParseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HumanParseServer will
// result in compilation errors.
type UnsafeHumanParseServer interface {
	mustEmbedUnimplementedHumanParseServer()
}

func RegisterHumanParseServer(s grpc.ServiceRegistrar, srv HumanParseServer) {
	s.RegisterService(&HumanParse_ServiceDesc, srv)
}

func _HumanParse_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanParseServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HumanParse_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanParseServer).Generate(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HumanParse_ServiceDesc is the grpc.ServiceDesc for HumanParse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HumanParse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HumanParse",
	HandlerType: (*HumanParseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _HumanParse_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parse.proto",
}
