// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: parse_agnostic.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ParseAgnostic_Generate_FullMethodName = "/ParseAgnostic/Generate"
)

// ParseAgnosticClient is the client API for ParseAgnostic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParseAgnosticClient interface {
	Generate(ctx context.Context, in *ParseAgnosticRequest, opts ...grpc.CallOption) (*ParseAgnosticReply, error)
}

type parseAgnosticClient struct {
	cc grpc.ClientConnInterface
}

func NewParseAgnosticClient(cc grpc.ClientConnInterface) ParseAgnosticClient {
	return &parseAgnosticClient{cc}
}

func (c *parseAgnosticClient) Generate(ctx context.Context, in *ParseAgnosticRequest, opts ...grpc.CallOption) (*ParseAgnosticReply, error) {
	out := new(ParseAgnosticReply)
	err := c.cc.Invoke(ctx, ParseAgnostic_Generate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParseAgnosticServer is the server API for ParseAgnostic service.
// All implementations must embed UnimplementedParseAgnosticServer
// for forward compatibility
type ParseAgnosticServer interface {
	Generate(context.Context, *ParseAgnosticRequest) (*ParseAgnosticReply, error)
	mustEmbedUnimplementedParseAgnosticServer()
}

// UnimplementedParseAgnosticServer must be embedded to have forward compatible implementations.
type UnimplementedParseAgnosticServer struct {
}

func (UnimplementedParseAgnosticServer) Generate(context.Context, *ParseAgnosticRequest) (*ParseAgnosticReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedParseAgnosticServer) mustEmbedUnimplementedParseAgnosticServer() {}

// UnsafeParseAgnosticServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParseAgnosticServer will
// result in compilation errors.
type UnsafeParseAgnosticServer interface {
	mustEmbedUnimplementedParseAgnosticServer()
}

func RegisterParseAgnosticServer(s grpc.ServiceRegistrar, srv ParseAgnosticServer) {
	s.RegisterService(&ParseAgnostic_ServiceDesc, srv)
}

func _ParseAgnostic_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseAgnosticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParseAgnosticServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParseAgnostic_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParseAgnosticServer).Generate(ctx, req.(*ParseAgnosticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParseAgnostic_ServiceDesc is the grpc.ServiceDesc for ParseAgnostic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParseAgnostic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ParseAgnostic",
	HandlerType: (*ParseAgnosticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _ParseAgnostic_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parse_agnostic.proto",
}
