// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: vtion.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Viton_Generate_FullMethodName = "/Viton/Generate"
)

// VitonClient is the client API for Viton service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VitonClient interface {
	Generate(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataReply, error)
}

type vitonClient struct {
	cc grpc.ClientConnInterface
}

func NewVitonClient(cc grpc.ClientConnInterface) VitonClient {
	return &vitonClient{cc}
}

func (c *vitonClient) Generate(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataReply, error) {
	out := new(DataReply)
	err := c.cc.Invoke(ctx, Viton_Generate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VitonServer is the server API for Viton service.
// All implementations must embed UnimplementedVitonServer
// for forward compatibility
type VitonServer interface {
	Generate(context.Context, *DataRequest) (*DataReply, error)
	mustEmbedUnimplementedVitonServer()
}

// UnimplementedVitonServer must be embedded to have forward compatible implementations.
type UnimplementedVitonServer struct {
}

func (UnimplementedVitonServer) Generate(context.Context, *DataRequest) (*DataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedVitonServer) mustEmbedUnimplementedVitonServer() {}

// UnsafeVitonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VitonServer will
// result in compilation errors.
type UnsafeVitonServer interface {
	mustEmbedUnimplementedVitonServer()
}

func RegisterVitonServer(s grpc.ServiceRegistrar, srv VitonServer) {
	s.RegisterService(&Viton_ServiceDesc, srv)
}

func _Viton_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VitonServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Viton_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VitonServer).Generate(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Viton_ServiceDesc is the grpc.ServiceDesc for Viton service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Viton_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Viton",
	HandlerType: (*VitonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _Viton_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vtion.proto",
}
