// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"govton/core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/index",
				Handler: indexHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: uploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/viton",
				Handler: vitonHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vitons",
				Handler: vitonsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/openpose",
				Handler: openposeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/densepose",
				Handler: denseposeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/parse",
				Handler: parseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/clothmask",
				Handler: clothmaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/human_agnostic",
				Handler: humanAgnosticHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/parse_agnostic",
				Handler: parseAgnosticHandler(serverCtx),
			},
		},
	)
}
