// Code generated by goctl. DO NOT EDIT.
package types

type IndexRequest struct {
}

type IndexResponse struct {
}

type UploadRequest struct {
	File []byte `json:"file"`
	Path string `json:"path"`
}

type UploadResponse struct {
	Path string `json:"path"`
}

type VitonRequest struct {
	Cloth []byte `json:"cloth"`
	Image []byte `json:"image"`
}

type VitonResponse struct {
	Image []byte `json:"image"`
}

type VitonsRequest struct {
	Cloth []byte `json:"cloth"`
	Image []byte `json:"image"`
}

type VitonsResponse struct {
	Result []byte `json:"result"`
}

type OpenPoseRequest struct {
	InputPath    string `json:"inputPath"`
	OutputPath   string `json:"outputPath"`
	KeypointPath string `json:"keypointPath"`
}

type OpenPoseResponse struct {
	Image    []byte `json:"image"`
	Keypoint string `json:"keypoint"`
}

type DensePoseRequest struct {
	Image []byte `json:"image"`
}

type DensePoseResponse struct {
	Image []byte `json:"image"`
}

type ClothMaskRequest struct {
	Image []byte `json:"image"`
}

type HumanParseRequest struct {
	Image []byte `json:"image"`
}

type HumanParseResponse struct {
	Image []byte `json:"image"`
}

type ParseAgnosticRequest struct {
	Image            []byte `json:"image"`
	Cloth            []byte `json:"cloth"`
	Mask             []byte `json:"mask"`
	ImageParse       []byte `json:"parsing"`
	OpenPoseImage    []byte `json:"openpose"`
	OpenPoseKeypoint string `json:"keypoint"`
	DensePoseImage   []byte `json:"densepose"`
}

type ParseAgnosticResponse struct {
	Image []byte `json:"image"`
}

type HumanAgnosticRequest struct {
	Image              []byte `json:"image"`
	Cloth              []byte `json:"cloth"`
	Mask               []byte `json:"mask"`
	ImageParse         []byte `json:"parsing"`
	OpenPoseImage      []byte `json:"openpose"`
	OpenPoseKeypoint   string `json:"keypoint"`
	DensePoseImage     []byte `json:"densepose"`
	ImageParseAgnostic []byte `json:"agnostic"`
}

type HumanAgnosticResponse struct {
	Image []byte `json:"image"`
}
